/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iet.hf.monkesoft.electric.boogaloo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
