package iet.hf.monkesoft.electric.boogaloo;

import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Agent.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * A virolĂłgusok altal felhasznalhatĂł targyak absztrakt Ĺ‘â€�sosztalya.
 * 
 *  @Time:  Az agens megszĹ‘Â±naÂ©saÂ©hez ennyi kaÂ¶rre van szaÄ˝ksaÂ©g. 
 *  Ha az aÂ©rtaÂ©ke elaÂ©ri a nullat, akkor az agens meghaÂ­vja a MegszĹ‘Â±nik() metĂłdusat aÂ©s ezzel a eltĹ‘Â±nik a jataÂ©kbĂłl.
 *  
 *  @Cost:  Ez az Anyag objektum tarolja azt, hogy milyen mennyisaÂ©gĹ‘Â± anyagra van szaÄ˝ksaÂ©g az adott agens elkaÂ©szaÂ­taÂ©saÂ©hez.
 *  
 *  @eff:	Az agens felhasznalasakor ez az effekt keraÄ˝lhet a caÂ©lpontra 
 */


public abstract class Agent {
	protected int Time;
	private int Cost;
	protected Effect Eff;

	static HashMap<Integer, Agent> list = new HashMap<Integer, Agent>();
	int Id = 0;
	protected Agent (Agent a, int id) {
		setId(id);
		this.Time = a.Time;
		this.Cost = a.Cost;
		this.Eff = a.Eff;
	}
	protected Agent(Effect e) {
		Eff= e;
		Time = 10;
		Cost = 10;
	}
	private void setId(int id)
	{
		while(list.containsKey(id)) 
			id++; 
		this.Id = id;
		list.put(Id, this);
	}
 	/**
	 * Az agens kifejti a hatasat a paramaÂ©teraÄ˝l kapott virolĂłgusra.
	 * Akkor haÂ­vĂłdik meg, ha az agenst birtoklĂł virolĂłgus felhasznalja az adott agenst. A paramaÂ©terkaÂ©nt kapott virolĂłgus az, 
	 * aki elszenvedi az agens hatasait.
	 */

	public void Activate(Virologist v, Virologist v2) {
		new AppliedEffect(v, Eff);
	}

	/**
	 * KaÂ¶r vaÂ©gaÂ©n ez a metĂłdus gondoskodik arrĂłl, hogy a Lejarati_idĹ‘â€� eggyel csaÂ¶kkenjen.
	 */
	public void DecrTime(Virologist v) {
		Time--;
	}

	/**
	 * Ha lejar az agens felhasznalasara szolgalĂł idĹ‘â€�, akkor az agens eltĹ‘Â±nik a jataÂ©kbĂłl. 
	 * A jataÂ©kbĂłl eltaÄ˝ntetaÂ©saÂ©aÂ©rt felel ez a metĂłdus.
	 */
	public void Die(Virologist v) {
		
	}

	/**
	 * Akkor haÂ­vĂłdik meg, amikor a virolĂłgus egy genetikai kĂłd alapjan elĹ‘â€�allaÂ­t egy agenst. 
	 * A virolĂłgus megfelelĹ‘â€� anyagaibĂłl kivonja a kaÂ¶ltaÂ©gaÂ©t, ha ez lehetsaÂ©ges. 
	 * Ha sikeraÄ˝lt, laÂ©trehoz egy masolatot az agensrĹ‘â€�l amit hozzaad a virolĂłgus inventoryjahoz.
	 */
	public void Make(Virologist v) {}

	public int getCost() {
		return Cost;
	}

	public void setCost(int cost) {
		Cost = cost;
	}

	public Effect getEff() {
		return Eff;
	}

	public void setEff(Effect eff) {
		Eff = eff;
	}

	public int getTime() {
		return Time;
	}

	public void setTime(int time) {
		Time = time;
	}
	@Override
	public String toString() {
		return "(" + this.Id + ") ";
	}
}
