package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.AminoAcid.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * Olyan anyag, amellyel vakcinák készíthetők. 
 * Egy bizonyos értéknél nem lehet többet tárolni belőle.
 */

public class AminoAcid extends Material {
	/**
	 * Az Anyag osztályból származtatott metódus felüldefiniált verziója.
	 *Ha van legalább i Mennyiség, csökkenti a Mennyiség attribútum értékét i-vel és visszatér true-val.
     *Ha nincs elég, nem történik semmi és visszatér false-al.
     *A visszatérési érték megmondja, hogy az anyag menniysége megengedi-e az ágens létrehozását.
	 */
	
	public AminoAcid(int amount, int max) {
		super(amount, max);
	}
	public AminoAcid(int amount) {
		super(amount,amount);
	}
	public AminoAcid() {
		super(0, MAX);
	}
	
	@Override
	public boolean SubtractAminoAcid(int i) {
		if(i>this.getAmount()) {
			return false;
		}
		else {
			setAmount(getAmount()-i);
			return true;
		}
	}
	
	
/**
 * Megnöveli a Mennyiség attribútum értékét i-vel.
 */
	@Override
	public void AddAminoAcid(int i) {
		setAmount(getAmount()+i);
	}

	@Override
	public int getAminoAcid() {return getAmount();}

	@Override
	public int getMaxAminoAcid() {return getMax();}
}
