package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bag.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/**
 * Olyan védőfelszerelés, amelytől megnő a virológus anyaggyűjtő képessége. 
 */

/**
 * v felvette a zsákot, így megkapja a zsák effektjét, 
 * ezzel a maximum anyaghordozó-képessége megkétszereződik.
 */
public class Bag extends Equipment {

	public Bag(Effect e, int id) {
		super(e, id);
	}

	@Override
	public void Equipped(Virologist v) {
		this.GetEffect().Apply(v);
	}
/**
 * v levette a zsákot, így eltűnteti a zsák effektjét a virológusról, 
 * ezzel a maximum anyaghordozó képessége megfeleződik.
 */
	@Override
	public void UnEquipped(Virologist v) {
		this.GetEffect().Die(v);
	}

	@Override
	public String getType() {
		return "bag";
	}
}
