package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Cape.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/**
 * Olyan vÃ©dÅ‘felszerelÃ©s, amely a hordozÃ³ra kent Ã¡gensek kenÃ©sÃ©t 82,3%-al megakadÃ¡lyozza.
 */


public class Cape extends Equipment{

	public Cape(Effect e, int id) {
		super(e, id);
	}

	/**
	 * A kÃ¶penyt a paramÃ©terÃ¼l kapott virolÃ³gus felvette.
	 *Ekkor a kÃ¶peny Ã�ltalÃ¡nos vÃ©delmet tÃ¡rolÃ³ AppliedEffektet tesz rÃ¡.
	 */

	@Override
	public void Equipped(Virologist v) {
		this.GetEffect().Apply(v);
	}
	
	/**
	 * A kÃ¶penyt a paramÃ©terÃ¼l kapott virolÃ³gus levette.
     * Ekkor egy Ã�ltalÃ¡nos vÃ©delmet tÃ¡rolÃ³ AppliedEffektet levesz rÃ³la.
	 */
	@Override
	public void UnEquipped(Virologist v) {
		this.GetEffect().Die(v);
	}

	@Override
	public String getType() {
		return "cape";
	}
	
	@Override
	public void Discard(Virologist v) {
		v.UnEquip(this);
		v.getEquipmentInventory().remove(this);
	}
}
