package iet.hf.monkesoft.electric.boogaloo;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Confusion.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * Olyan effekt singleton osztálya, amelytől a virológus kontrollálatlanul kezd el mozogni.
 * 
 * @author tomif
 *
 */

public class Confusion extends Effect {
	public Confusion() {
		super("confusion");
	}
/**
	 * A visszatérési értéke mindig true.
	 *	A paraméterként kapott virológus mezőjének egyik szomszédját kiválasztja véletlenszerűen és átmozgatja rá.
	 */	@Override
	public boolean ModMove(Virologist v) {
		//virologus mezoje
		Field Current=v.getField();
		ArrayList<Field> neighbours = 
				Current.GetNeighbours();
		//kivalaszt egy random szomszed mezot
		
		Field selected = neighbours.get(Interface.Random.nextInt(0, neighbours.size()-1));
		
		//atteszi a kivalsztott mezore
		if(selected.Accept(v)){
			if(v.Place != null)
				v.Place.Remove(v);
			v.setMovementPoints(v.getMovementPoints() - 1);
			v.SetField(selected);
		}
		return true;
	}
}
