package iet.hf.monkesoft.electric.boogaloo;

import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Equipment.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * Olyan tárgyak absztrakt ősosztálya, 
 * amelyeket óvóhelyeken találni és pozitív effekteket fejtenek ki a virológusokra, 
 * ha viselik őket.
 *
 */

public abstract class Equipment {
	private Effect Eff;

	static HashMap<Integer, Equipment> list = new HashMap<Integer, Equipment>();
	int Id = 0;
	protected Equipment(Effect e, int id) {
		this.Eff = e;
		while(list.containsKey(id)) 
			id++; 
		this.Id = id;
		list.put(Id, this);
	}

	/**
	 *A paraméterként kapott virológus felvette a védőfelszerelést, 
	 *ezért átkerül a Viselt_felszerelésekbe és ráteszi az effektjét a viselőre.
	 */

	public void Equipped(Virologist v) {
		if(Eff != null)
			this.Eff.Apply(v);
	}
	/**
	 * A paraméterként kapott virológus levette a védőfelszerelést, 
	 * ezért átrakja a védőfelszerelést a Felszerelés_inventory-ba és leveszi az effektjét a volt viselőről.
	 */
	public void UnEquipped(Virologist v) {
		this.Eff.Die(v);
	}
	
	/**
	 * Equipments useable from the inventory
	 * use this method
	 * 
	 */
	public void Use(Virologist v) {
	}
	
	/**
	 * The equipment has been used as many times as possible
	 * (for example: glove -> 3 times), so it has to be discarded
	 * Discards the equipment from it's user's inventory
	 */
	public void Discard(Virologist v) {
		
	}
	
	public Effect GetEffect() {return Eff;}
	public abstract String getType();
	
}
