package iet.hf.monkesoft.electric.boogaloo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : General.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * @author tomif
 * Általános védelem megvalósítása
 * 
 *
 * A minden ágens elleni védelmet nyújtó effekt singleton osztálya.
Akkor nem véd az ágensek ellen, ha az ágenst felhasználó és a megcélzott játékos megegyezik.


 */ 

public class General extends Protection {
	General(){
		super("general", 0.823);
	}
/**
 * az Esély attribútum értékével megegyező eséllyel true-val, egyébként false-al tér vissza. 
 * Minden effekt ellen azonos módon véd. Ha a visszatérési érték true, akkor a védelem sikeres volt.
 */		
	@Override
	public boolean Protect(Agent a, Virologist v, Virologist v2) {
		return Interface.Random.nextBoolean(Chance);
	}

	@Override
	public void Apply(Virologist v) {
		new AppliedEffect(v, this, -1);
	}
	
	@Override
	public void Die(Virologist v) {
		v.RemoveEffect(this);
	}

	@Override
	public boolean isIndividual(){
		return false;
	}
}
