package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Glove.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/**
 * A vírusokat visszakenő kesztyű osztálya.
 */


public class Glove extends Equipment {

	public Glove(Effect e, int id) {
		super(e, id);
	}
	/**
	 * A paraméterként kapott virológus felveszi a kesztyűt. 
	 * Ekkor Visszakenés effektet tároló AppliedEffektet ad rá.
	 */
	 
	@Override
	public void Equipped(Virologist v) {
		this.GetEffect().Apply(v);
	}
	
	/**
	 * A paraméterként kapott virológus leveszi a kesztyűt. 
	 * Ekkor egy Visszakenés effektet tároló AppliedEffektet levesz a virológusról.
	 */

	@Override
	public void UnEquipped(Virologist v) {
		this.GetEffect().Die(v);
	}

	@Override
	public String getType() {
		return "glove";
	}
	
	/**
	 * The glove has been used as many times as possible
	 * so it has to be discarded
	 * Discards the equipment from it's user's inventory
	 */
	@Override
	public void Discard(Virologist v) {
		v.UnEquip(this);
		v.getEquipmentInventory().remove(this);
	}
}
