package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Laboratory.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/** 
 *A genetikai kódokat tároló mezőket megvalósító osztály.
 */

public class Laboratory extends Field {
	/**
	 * The genetic code that can be found in the laboratory
	 */
	protected GeneticCode Code;
	
	/**
	 * Special effect that spreads to anyone interacting
	 * with the laboratory
	 */
	private Effect effect;
	
	/**
	 * Only sets a gencode, makes the stored effect NULL
	 * @param gencode
	 */
	public Laboratory(GeneticCode gencode, int id) {
		super(id);
		this.Code = gencode;
		this.effect = null;								//ez konstruktor paraméter kéne, hogy legyen. Mondjuk boolean, hogy legyen-e medve
	}
	
	/**
	 * Constructor for also setting an effect that spreads
	 * @param gencode
	 * @param e
	 * The effect that spreads through interaction
	 * Only set iet.hf.monkesoft.electric.boogaloo.BearConfusion in this stage of the game
	 */
	public Laboratory(GeneticCode gencode, Effect e, int id) {
		super(id);
		this.Code = gencode;
		this.effect = e;
	}

	/**
	 * A paraméterül kapott virológus interaktált a laboratóriummal, 
	 * így megtanulja a mezőn tárolt genetikai kódot.
	 */
	@Override
	public void Interacted(Virologist v) {
		v.AddGenCode(Code);
		//Spread the virus
		if(effect != null) {
			Virus virus = new Virus(effect);
			v.ReceivedAgent(virus, null);
		}
	}
	@Override
	public String toString() {
		return "\t(" + Id + ") iet.hf.monkesoft.electric.boogaloo.Laboratory\n\t\t" + Code.getName()
				+ (effect != null ? "\n\t\tinfects " + effect.name : "");
	}
}
