package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Protection.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/**
 * Az olyan effektek absztrakt ősosztálya, amik megvédhetnek negatív effektektől.
 */


public abstract class Protection extends Effect {
	protected double Chance;
	Protection(String name, double c)
	{
		super(name);
		Chance = c;
	}
	@Override
	public void Apply(Virologist v) {
	}

	@Override
	public void Die(Virologist v) {
	}

	@Override
	public boolean Protect(Agent a, Virologist v, Virologist v2) {
		return false;

	}
	@Override
	public boolean isIndividual(){
		return false;
	}
}
