package iet.hf.monkesoft.electric.boogaloo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

/**
 *Azon mezÅ‘k osztÃ¡lya, amiken talÃ¡lhatÃ³ak vÃ©dÅ‘felszerelÃ©sek.
 */


public class Shelter extends Field {
	/**
	 * If Eq==null, then there are no equipments to collect
	 */
	private Equipment Eq = null;
	
	/**
	 *  A paramÃ©terkÃ©nt kapott virolÃ³gus interaktÃ¡lt az Ã³vÃ³hellyel,
	 *  Ã­gy az ott talÃ¡lhatÃ³ vÃ©dÅ‘felszerelÃ©st felveszi az inventory-jÃ¡ba. 
	 *  Ha nincs vÃ©dÅ‘felszerelÃ©s az Ã³vÃ³helyen, akkor nem tÃ¶rtÃ©nik semmi.
	 */
	public Shelter(Equipment eq, int id){
		super(id);
		this.Eq = eq;
	}
	@Override
	public void Interacted(Virologist v) {
		//If there is no equipment to be equipped
		if(this.Eq == null) {
			return;
		}
		//Else, add to inventory
		v.AddEquipment(Eq);
		
		//Equipment is no longer in the shelter
		this.Eq = null;
		
	}
	@Override
	public String toString() {
		if (Eq != null)
			return "\t(" + Id + ") Shelter\n"
					+ "\t\t(" + Eq.Id + ") " + Eq.getType();
		return "\t(" + Id + ") Shelter";
	}
}
