package iet.hf.monkesoft.electric.boogaloo;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Stun.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * 
 * A minden ágens elleni védelmet nyújtó effekt singleton osztálya.
 * Akkor nem véd az ágensek ellen, ha az ágenst felhasználó és a megcélzott játékos megegyezik.
 *
 */

public class Stun extends Effect {
	Stun() {
		super("stun");
	}

	/**
	 * az Esély attribútum értékével megegyező eséllyel true-val, egyébként false-al tér vissza. 
	 * Minden effekt ellen azonos módon véd. 
	 * Ha a visszatérési érték true, akkor a védelem sikeres volt.
	 */
	@Override
	public boolean ModRound(Virologist v) {
		return true;
	}
}
