package iet.hf.monkesoft.electric.boogaloo;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iet.hf.monkesoft.electric.boogaloo.Town.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//


/**
 * A játék mezőit egybezáró singleton osztály. A pályát reprezentálja.
 */

public class Town {
	private ArrayList<Field> Fields = new ArrayList<>();
	
	/**
	 * A játék inicializálásakor használatos metódus. Hozzáadja a Város objektumhoz a paraméterként kapott mezőt.
	 *
	 */
	public void AddField(Field f) {
		Fields.add(f);
	}
	public ArrayList<Field> GetFields()
	{
		return Fields;
	}
}
