import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//




public class Timer {
	
	ArrayList<Virologist> Virologists = new ArrayList<Virologist>();
	
	public void Tick() {
	}
}
